site_name: VATValidation
site_url: https://dseichter.github.io/VATValidation/
site_description: A tool to validate VAT numbers and check their status.
site_author: Daniel Seichter
copyright: Copyright © 2025 Daniel Seichter
repo_url: https://github.com/dseichter/VATValidation
repo_name: dseichter/VATValidation
theme:
  name: material
  logo: assets/Tick_Box.png
  favicon: assets/Tick_Box.png
  palette:
    - scheme: slate
      primary: cyan
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      default: true
    - scheme: default
      primary: cyan
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode  

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true 
          nav_translations:
            Home: Startseite
            Command Line: Kommandozeile
            Configuration: Konfiguration
            Graphical User Interface: Grafische Benutzeroberfläche
            Development: Entwicklung
            About: Über         

nav:
  - Home: index.md
  - Command Line: commandline.md
  - Configuration: configuration.md
  - Graphical User Interface: gui.md
  - Development: development.md
  - About: about.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg