# Copyright (c) 2024-2026 Daniel Seichter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import os
import base64
from PIL import Image

def generate_icons_py():
    """Generate src/icons.py with base64-encoded icon data for PySide6"""
    icon_data = {}
    icon_files = []
    
    # Collect all PNG files from the icons directory
    for root, dirs, files in os.walk('.'):
        for file in sorted(files):
            if file.endswith('.png'):
                filepath = os.path.join(root, file)
                icon_name = file[:-4].lower()  # Remove .png extension and convert to lowercase
                
                # Read PNG file and encode as base64
                with open(filepath, 'rb') as f:
                    png_data = f.read()
                    base64_data = base64.b64encode(png_data).decode('ascii')
                    icon_data[icon_name] = base64_data
                    icon_files.append((icon_name, filepath))
                    print(f"Processed: {icon_name} from {filepath}")
    
    # Generate the Python file
    output_path = '../src/icons.py'
    with open(output_path, 'w') as f:
        f.write("""#----------------------------------------------------------------------
# This file was generated by generate_icon.py
# It contains base64-encoded PNG icons for use with PySide6
#

import base64
from PySide6.QtGui import QPixmap, QIcon
from PySide6.QtCore import QByteArray


def get_icon_from_base64(data_str):
    \"\"\"Convert base64 string to QIcon\"\"\"
    try:
        byte_array = QByteArray.fromBase64(data_str.encode('ascii'))
        pixmap = QPixmap()
        pixmap.loadFromData(byte_array)
        return QIcon(pixmap)
    except Exception as e:
        print(f"Error loading icon: {e}")
        return QIcon()


# Icon catalog - maps icon names to base64-encoded PNG data
ICON_DATA = {
""")
        
        # Write each icon's base64 data
        for icon_name, base64_str in sorted(icon_data.items()):
            # Format base64 data in lines of 76 characters for readability
            formatted_data = []
            for i in range(0, len(base64_str), 76):
                formatted_data.append(base64_str[i:i+76])
            
            data_repr = " \\\n    ".join(f"'{line}'" for line in formatted_data)
            f.write(f"    '{icon_name}': {data_repr},\n")
        
        f.write("""}\n\n\ndef get_icon(name):
    \"\"\"Get QIcon by name from the catalog\"\"\"
    if name in ICON_DATA:
        return get_icon_from_base64(ICON_DATA[name])
    print(f"Warning: Icon '{name}' not found in catalog")
    return QIcon()

""")
    
    print(f"\n✓ Generated {output_path} with {len(icon_data)} icons")
    return icon_files

# Generate ICO file from the main logo
def generate_ico():
    """Generate vatvalidation.ico from the main logo PNG"""
    logo_file = "select_check_box_48dp_097E23_FILL1_wght400_GRAD0_opsz48.png"
    if os.path.exists(logo_file):
        with Image.open(logo_file) as img:
            # Save as ICO with multiple sizes
            img.save("vatvalidation.ico", format="ICO", sizes=[(16,16), (32,32), (48,48), (64,64), (128,128), (256,256)])
            print("✓ Generated vatvalidation.ico")
    else:
        print(f"Warning: {logo_file} not found, skipping ICO generation")

if __name__ == "__main__":
    print("Generating PySide6-compatible icon files...\n")
    generate_icons_py()
    generate_ico()
    print("\nDone!")
