#----------------------------------------------------------------------
# This file was generated by generate_icon.py
# It contains base64-encoded PNG icons for use with PySide6
#

import base64
from PySide6.QtGui import QPixmap, QIcon
from PySide6.QtCore import QByteArray


def get_icon_from_base64(data_str):
    """Convert base64 string to QIcon"""
    try:
        byte_array = QByteArray.fromBase64(data_str.encode('ascii'))
        pixmap = QPixmap()
        pixmap.loadFromData(byte_array)
        return QIcon(pixmap)
    except Exception as e:
        print(f"Error loading icon: {e}")
        return QIcon()


# Icon catalog - maps icon names to base64-encoded PNG data
ICON_DATA = {
    'contact_support_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACBElEQVRIS7VVTUvcUBS970VNdCe4' \
    'UfBjRqRLt1bcCf6CQou6EYWuWiiiWHDiNBEtKtiC29lUUEH8AYJbBbddCpPJotCCm1IXeaOTXG8s' \
    'U2aS9+ZFi1nmnXvOveeelzB45oc9Mz9oBczV/AfGYJsxZtSbQUABiG+FW/mma1Ap0FEYemMw41BH' \
    'EPJo9LZY+a7CSQVMe3iHAyzqyP9NhLgmXM+R4VMClj0wyaD9LCt5HVfDcOzO9S+TdSmBTnsYU+SI' \
    'PwPX66u/twr5M9rJZBIXOOUUX9MLczW3xDnfkhYW+3qssPMYjHBOFH1f1ghG0YJYr5Qa65sEqLOI' \
    'Okt1QakpMWDz9cK4U8KeEnSqkYxGvxVO2VQKSO1JjhNFy8F6ZVuFTdrU1K1OIELYq7rld2Yh95Uz' \
    '/l4WhP8S+GtNbpYxvq9KWUsB1Q4S3tcab7UuSc0psilFkE5R1jtBYTgUjjetXHJ8oNpDhHhSdb1X' \
    'lp0/p0SNS/2/qXbB7o+gpUCHPfTaAOMoSYCI5/Q5mCCBKxIYSZ0D1Cii7dqbHANoF5vk80pWa2Jc' \
    '8Cfshi/+70wCD1YVBl8Ca7vIIkLTHdB0MzKs/n9g0/8AYINsseRi+CtwvF5VI1qBZGFjCCg1V5Sa' \
    'F62mfLIAMvwsPnkfdRY+ReA64GE/FH2hI4/PHy2QhbTlPXgsgQ5/Dz9Dvxn1eJMlAAAAAElFTkSu' \
    'QmCC',
    'exit_to_app_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAyUlEQVRIS2NkoDFgpLH5DPS1gLVa' \
    'wYKFmfk4Jb768/+vxe/mBydhZqD4gLNO+T8lhsP0fm+6CzcXqwXICkixEObAwWkByHWEfEa2Dzhq' \
    'lT8xMjLwgoILnyUELcAX3hx1yp+BEcaDzxKKLAAZTMgSghaQmkzRg2vgLSCU5ikOIppHMrYwBEcu' \
    'tZIpLgtAltA0oxGKG5g80amIUJGAy0KiLSDWxbjU4SxNWWrlLVkZWY5RYsGfv38tf7c+OIG1wqHE' \
    'YFx66Vsn08IHAGsmmBkexiLBAAAAAElFTkSuQmCC',
    'globe_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACQUlEQVRIS71Vy27TQBSdh53XAvZI' \
    'bYwtNVVgAQKJErGAH0BCsAMWiK+AxFEUB3XJHyAkuo7Ehm1XPAXqAqEWShyC+IOqJMb2XGYQNn6M' \
    'MwapeJX4Xp9z7rlz72B0xA8+YnykJNDt5lmK6RgjbCTFAEJuCMEN35ntLBNZSFDtnWwRQvbKVMgY' \
    'rHkjd1+WKyWo2eYTjPEt8QEg+B6GcMV/MH0TAVR7KxYhlc+pigAeLxz3TpYkR1C1zTHB+JpIDMA/' \
    '7ztf32U/qvct7lD+YQBjz3GvJyMpgspgtU2Z/kEkzA+8Bnr4bR4l611jQ6P0pcoyxti6N5p+jPJS' \
    'BLEyH12ab06eJ8GKVMsI58NJjBv/0O3VcxrW3wKgg4UzOVbWFhlB0tqYgDd2jze25UPQCZxZzoq/' \
    'qYCL3OUi24I8JogAkuUt81tFGOH8f4Ii1Xwepouha0ZxzW5e1LH2IpkfEv9UfAp/NzpXgeoYqizM' \
    'Wv2nyX1zmt03MjKxgxbDiSWL1QbGZczoNgDs86leSzVZ61odnaLU2S+qpqiKWt885CIbAYQbvvPl' \
    'dYpA/FGdjIhQRlDrcfWEbv/aArJBE4HK/ZXTVKu8V01nLj440aiz+qF4H7Kg/WM025WuCvGyaltP' \
    'CUZXsyBFtui2cUHD9JXIVy67CJR7ucW9vJkkyRJo3WZHJ9ozPqrHRR5v7BZv7O2ssMILp3LPWKc6' \
    'jUtddnyZDy1v0/0kyyl1ZXILHvGtciYDsBNAcPefr0zVwJWNKysoC1SU9xOO6O0ZJNmh+AAAAABJ' \
    'RU5ErkJggg==',
    'info_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABq0lEQVRIS92Vy07CQBSGZzq9wBu4' \
    'EZEmQIgLDRvjQ5gY3enCxKfwUkJoE9/CxKhbEh/ChYmRhTGIpEV2vgEtLXMshE5oKb1A2Dirdvqf' \
    '88259AxGa154zf5RLEBQtvYIJk2McH72MICQMQLnxFb7rahDLgRIN9sljuO+kkRIKRQtzeiGaUMB' \
    'GaXwgDE+S+Lc0wCi92ajdx60mQNISqHJYXyUxrmnpQBNSzWOZ219ALGeqxAqfC7jnEEoLVtar+O9' \
    '+wDZmuzWbvEa/Ori+Gt2Qx5G6ho688seBCVX5bHwFmnI6dIEQGUrSudwTtWu99/HGgbI1AodtxWL' \
    'q6SHFRxQ21T1ig8Ql5604ME0TSyCJADPKI32HwHcIveC8yaY96QpAoCuqRqThmEp4q/lA4GglyT9' \
    'HVcDB0b7tvrz6gNM+jvuR5t2RlLdHEC82twhvPiRtiVn9SPqVIZavx06KsabkiI/cxgdLgOJHXae' \
    'U7fgj27BT9NAgMKTqRlzI37hhSNe5stEICzUKBi1oWTdGt9hmkRXJo/JndtwuwEHLQeci6WvzDTp' \
    'idLGRrAq6A/UNqkZQQBA9wAAAABJRU5ErkJggg==',
    'output_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAA0ElEQVRIS2NkoDFgpLH5DPS1gLVa' \
    'wYKFmfk4Jb768/+vxe/mBydhZqD4gLNO+T8lhsP0fm+6CzcXqwXICkixEObAoWUBR61SOzCp/PjR' \
    'dK8Rm28pC6IGZTHOfwwvQQb/Z/jfgM0SyiwAGsxWq6TLzMh4CZclFFsAMpi1St6IhYXlLDZLiLKA' \
    '1OSLHFyDwwJCeYHiIMJnAW0jmR7JlLYZDS3sBk9ZRCjVEJLHWZqy1MpbsjKyHCNkAD75P3//Wv5u' \
    'fXACa4VDicG49NK3TqaFDwCJx6QZ5nuPoQAAAABJRU5ErkJggg==',
    'overview_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABhUlEQVRIS2NkoDFgpLH5DPS1gLVa' \
    'wYKFmfk4Jb768/+vxe/mBydhZqD4gLNO+T8lhsP0fm+6Czd3mFuA7FV8QYcetEQHEc0tIDfCifYB' \
    'zS0gNoiQHcJRr9T+o/FeJVH5gBwL0H1Ncj74z/D/6I+mezYgg9gq5bSYWFnPAw1hA/GBufTXv99/' \
    '9X+1P7hBlA+wxQHMVxy1SssZGRkjsKn5/+//8h8t96JAcnh9gCuIWGsV9VkYmS7ADAf6qgFiGCOY' \
    'BoG////r/Wq+d5ksCzhqlX8xMjKw4rPg/3+Gnz+a73KQFAcwH6HnXGw+AFkOUk8VC4DR++570z1h' \
    'zjql98CAEkAuVcmygKNO+Scs5SBF8hugi0WBwfcJ6GxeYIr68aPpLieKBSy18pasjCzHcOVgYFAk' \
    'AZPofPYaRXUmJiZ4UkSo//8B5oN//36p/Gx5jKgYSC0WOOqUlgBTTTTWZPr//5IfzfdiMZIpqZaw' \
    '1iobszAynEHW9+fPH+PfbQ/PYc1opFpAjHoANaa7GSDww54AAAAASUVORK5CYII=',
    'playlist_add_check_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAx0lEQVRIS2NkoDFgpLH5DKMWEAxh' \
    '+gYRZ53yf4JOQlLwvekuQQeiKKC5BaS4nli1BL1IrEG41NE3iIZEHIAc+Z3pPT9Dw7tPoGCjahzA' \
    'QuA/w/8fP5rucWJYQCiIYOmeo1pRnoGZaeGPprsOsMjFZjjZFiAc8v/S96Z7+nDD/////qP5Hhdy' \
    'iiIviAplODl52b8hGwQMlm/AYOFGT67kWQAyBckSXIZTHskl4twcnNwvgcHCQ1RGozTXYtNPfhAR' \
    '6ZpRCwgGFADzp1AZV9eQZwAAAABJRU5ErkJggg==',
    'restart_alt_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAB8ElEQVRIS+2Uvy8EURDH5z139haF' \
    'SkR19jRqEiQoLiR+1KLWEIWESiJus7nVUNCKwh+A6PyIRBQiCJ1CY++uEolKcXbduR2z61bWnf0h' \
    'oZDY7r038/3Mm/m+ZfDLH/tlffgWIJqKdxXV3OV3igoNiMitg1HgR4h4YqiZZFhIKIAjbomWTHOs' \
    'sJTd+TFAZIEqj/CjSkEEODd4KQlKzvCDBd5AUOJD3Kw58BJBwDMjnen1OvcExFLSHfW6zUoUFgnC' \
    '3yElNMcLanZLkKVVDmzO2iPIM0Hqv4J8CSDxfcbYMGU+6qrW5IaQ2AmJfQxZlBPULRtySvv9lZBq' \
    'wCRExeZEwQrUb7UIbEPJSYoq8e6ikruoFHEgOtfrQbl/dp9XAaj6Pap+hOy4Ti2aDuMWISWtccZm' \
    'KeeYcgZ8AR/VpLVAA7iFvPKqRP4BekVrq4csS6cMWC+iuWGo2akwQ47J0iblTCDCoaFqw75DBqWl' \
    'TjTFvG3TtMZti/t9Y1Ajtide7fgHrRY2oOgPoFMxJV0DYx1liLebXOJk0X2y6GjwQytH0LXzdO06' \
    'a2kirryomXl3suN9+xUj5km8IfSvwgkUZekKgHU6a2eAjpXL+xe03+PVxeDHNNMmxBrNXet1fwIg' \
    '3ugF6IPlzJPfiIIBYWzkE/P3AW90rtkZxCMZTQAAAABJRU5ErkJggg==',
    'save_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAA8klEQVRIS2NkoDFgpLH5DPS1gLVa' \
    'wYKFmfk4qb76z/C/4UfTvUZs+lB8wFmn/J9Uw2HqcVlCNQtAFmGzBKcF35vuEowfbD5Gt4TqFoB8' \
    'guy4YWwBuamJ6CCiuwV/Gf6F/Wq6vxpkMVutQgQzI/NyXI4gKpKRNf/799/3Z8u9Lchi7DWKfkxM' \
    'TBuxWUKyBbjyBK6cP/gs+Pfvn/vPlvu7UIKoTsmbiYERJdhg8iT7AKTx7/9/4b+a768CR3KdQjgz' \
    'A/MKqkUyqUmWLB+QYglOC1hq5S1ZGVmOkWIYuto/f/9a/m59cAImTrBIpsQykN6hbwEAh3OPGQEJ' \
    'f+AAAAAASUVORK5CYII=',
    'search_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABmElEQVRIS82TTUvDQBCGZ9LaJnrw' \
    'oAiK2Da5iwgqBa/+HOtV1ISSSE+CWG/+H7EKguI5rQVFi978yKYfWTfRFPqRbmobdG/Jzswzs/O+' \
    'CBEfjLg+/CFgLzUvxWM3ADjnT0mBPpMmXYFCpRZ28r4TiJp8hYBrQUUopefEKG+GgfQAJE2+ZF2v' \
    'u8kOhR3bMIt+oaSq5ASEk5/vkqWbWR6kAyDl5SVwsOomWUJLgvw96SmQT4uSE7O8mGZzAQrVp0GQ' \
    'ToCqvLK1zziOk7MPK6dBicmDzLYgCEVK4ZEY5mJ4gKZQrzPd5KpLChnbOUHIJLeJfwt4Yc3Ndqun' \
    '+43baqL0zjLKy6F3IO6m05iIVUKr6M2ehOMHT1FBp58PrpkPVnk+YGZrMbPFh/KBHyyqcgkRN4Kd' \
    'DA1EmGCSqxPdTA41QRuyn0mhgLeAOO3/YwUvyOf7FhzVPkRNsdn4CR6Eq/dB3bUhFGxmOLFf7EgA' \
    'tyAPMjKABxkLwIOoSv178ZQQvSz5zzU2gA8hNXMKzqARCSCSJf/KaLykYe6/ACzguRkUcu9WAAAA' \
    'AElFTkSuQmCC',
    'select_check_box_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABFUlEQVRIS2NkoDFgpLH5DPS1gLVa' \
    'wYKFmfk4ub76/f+vw5/mBweR9aP4gLNO+T+5hv9n+O/yo+neXnT9WC343nSX7KADOvL1dyYGbYaG' \
    'u69AllHVAqDhIENFQQbDHEk1C0AuB5orgmw41XzAWQt0OSOqy2FxQbEP8BmO1wfsNUqqjIyMZ380' \
    '3+XDlbKAwfISKCeGEiy5KuwMk+/8JOgDWJL9/5/hMzZLcBnOKfj/B3IqxBtEuCzBajjQyTD1RFsA' \
    '8ia6JfjCnCwLkC1BjgtsmZFsC9AtwZXTKbIAZgm+YoRiCwgVhIPHAkIuJSSPM5my1MpbsjKyHCNk' \
    'AD75P3//Wv5ufXACa06mxGBcesmuWIh1DM0tAABdhMEZSH8tgAAAAABJRU5ErkJggg==',
    'select_check_box_48dp_097e23_fill1_wght400_grad0_opsz48': 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAACAklEQVRoQ+2Zv06FMBTGTx0M10FN' \
    'dHKE2YfQqA/goouJg+/gdK8EB+PkExgTF3XyAW6ML+F6cbm6aWI0ArkJtQwQ0ttCW/60GFih5fud' \
    '75z2UBB0/EId1w89gG4HeweMdsAaOjcIwbFOkRjwdej5JzwN3BSyRs4tuXmkU3zybgzwEnqTTWmA' \
    'wcghY/VeZeITdVwH8gCBNzG22DsDQFJ6i6TSM50T5gO4sDiInSgRHkO8F3mv4zyE2QA58aloOp3N' \
    'BWCJn4XrcPH2Yb4DguLNXIUkxJsHICneLAAF8eYAKIo3A0BAvDW0x+G5v8tqbNSXUXdjCdz336rd' \
    'Et1zBRFehUv/K52XdMRPpCPe5rUz8gC5iAXf0RpcTT+VIAQjjxDaSeavDWAuYioQAuIT0SINZSUH' \
    'su1dBoIlfoE46c472QxAopolQgRCQnxzDqRhl4WQFN88gIwTCuLbARCBUBTfHkARxMr0J/0YyQqe' \
    'U7Cspbi5ImYv/Ii8MC7aE+hNqmz/aBuAuTqpRD4d0z4AL50k0ibvih4ACiJQFN9uEXNqAk7t5Xxj' \
    'Vpbz9H19Dsgq5TzfA2QriKajxd6Bf+NATTVZaRr5L7Iz+w4wOqz01toG48fA8/dZ0xWe+5Mj7Xvy' \
    'wEFtOhQmIj85HsixOjeQxv64EGXtAUQj1dRzvQNNRVZ03s478Af5FdZAqrjQmwAAAABJRU5ErkJg' \
    'gg==',
    'settings_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABy0lEQVRIS8WVsUoDQRCGZyPoniBa' \
    'WFnJXWNaBUGsREVbCwvfQFFLQSF3JHcRFCyjoE9gYWEria2ggm1sbtHGTlAQb0PijRNDTM7sJReS' \
    'YJqQ7Ox+M/P/O8ugxx/W4/MhEkCzDFQl4tluy/0tA8oHdxeQHBuE5MtnfcaRAYq9DRVw05CMwQAi' \
    '5uSjWOYT+i1jbEqtFT54eTHN4/oVAzaPCAXpuLw+NgDgCX2BxVi2E+HRx0WZFrnqGQFAWCvaBdaL' \
    '/wvQLP0EgG00OwzRP6N2FakV6/TdFx6Lx54ttsrrNYBpvNGvYdUm0uNcOmKtfo2beooglhKC8O45' \
    '7kgAULGjniHm5t9NYX7nlu6RuAFRfYRMwXG3lRqU/yQXJchFTjXAR7woOGJVlSlVYVEVqeoatc4k' \
    'F6VDXfQDSBgmi4FdA8AlZbQSBQCIe54jDkIBXWrRESW009AirZsiA7ySbqNBF0WxKeAp2a7UyqYI' \
    'eChtsatwkXpqduWiVQTufFQUv0qzpf3nm3CbWkaB2tBPZV7LvFjS4sYdBU+GXMB7GogzNOyydB/m' \
    '6NH4kLY71NSm0NG4HueQfJLNAYpUI78Hir3/8KK1a5kW8ZEq6IT5DV0UzhkLTBZwAAAAAElFTkSu' \
    'QmCC',
    'task_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABPUlEQVRIS2NkoDFgpLH5DBgWsFYr' \
    'WLAwMx8nZPF/hv8NP5ruNRJSh2EBZ53yf0KaYPLEWEKWBSCDGRkYG0AWEbKELAu+N91l5KhTqifG' \
    'ErItALmeGEsosoAYSyi2AN0SUPAhJxKyLMCXyoaOBf8Y/vczMf3sY/jH8RjZR1Txwb///yb9bL6f' \
    'Dw7/WqX5jIyMCTBLSLbgz++/FsysTFOAad4EbMj//9O+N9/LBjHZ65QmMDEwgi0iywJgMEz82XSv' \
    'AKSZs1bpApA6Cje8VnEiEyNTHnqEk+yDf///Z/5svjcD2SBgsEwHBksGttREsgUgQ/79+5vxs+XB' \
    'TGiY4zQcJE+WBeCgZ/iXBqRMGRmYUodHPsDlC7KDCF+wkJRMWWrlLVkZWY4RayCyuj9//1r+bn1w' \
    'AlmM/pU+OS7HpwcAySixGcSW7K8AAAAASUVORK5CYII=',
    'update_24dp_097e23_fill1_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACFklEQVRIS8VVMU/bQBR+ZxLsQ4UJ' \
    'UQGFwVakDqhiSAc2JiqhrgwsVOofKAPKQhNZTpYIIfoPkNqRiaECAVK3Dq0Q6sRCHIa0aiWWDMSX' \
    'VLnri1NHF2NfPBDFm+1773vf9973jsCQHzLk/DB6AMNeNIGnj7GSJZmtEOKCNdgm7P+6U6kQz2AD' \
    'xoznlkcIpFUJEOieFd1JPCNowRKds55T6eWNBth9Nk/H9FqQWIB4yxz3UAbS8+a2RshB8M37y6Zp' \
    '2vDZqAFs0Ci32t1A8dlz3NcqBrRgXgGQZfmMEsDImw1CCEXqZ0j9lRwYJUHnP4L8QJAXPTaxEu08' \
    'naETT/6EaQaBYYDgPcwwlgFW8g0reSmAbzGn+ikc+AgAD6cgiUSJxzRO4ziJkmyBvjEdBGAU0BcA' \
    'hhDQZMWK8egAnYRG3mJoPj0KZKDRsMnfsclZIfgbVqx+jKuwBwLQYk5F90c1b+Vws5XRO5fonWwQ' \
    '2+9k25qhHGLHVAZEuZrAeYmVqsWuF7oDwrVmpmnXbqIBOhIUrDqiTqHRTtBo60l0xpivGLOCCAwZ' \
    'UTkmchcF1eAOOscdtKYCQbm+YE9WfXNeV1JwBP/XTDcqetnZC3OUj/+UEufQnXsykP7efKdp5EPw' \
    'zdPas2Df/g4Xo7xwgr2kYoAsG+zanQpXHtuDcDL/wmmnTnEBZuR/fo9asAllt64qYPRXZpIpGimD' \
    'f0oE6hmtQBmAAAAAAElFTkSuQmCC',
}


def get_icon(name):
    """Get QIcon by name from the catalog"""
    if name in ICON_DATA:
        return get_icon_from_base64(ICON_DATA[name])
    print(f"Warning: Icon '{name}' not found in catalog")
    return QIcon()

