name: 'Ruff Lint'
on:
  push:
    branches:
      - main
      - 'dseichter/**'
  pull_request:
    branches:
      - main
      - 'dseichter/**'

jobs:
  lint:
    name: 'Ruff'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6.0.2

      - name: 'Set up Python'
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14'

      - name: 'Install Ruff'
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: 'Ruff Lint'
        run: |
          # Exclude generated or packaging files from the Ruff check
          ruff check . --exclude icons.py --output-format=github